# Generated by Django 3.2.3 on 2021-05-26 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 5, 26), verbose_name='Date')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('quantity', models.IntegerField(max_length=1000, verbose_name='quantity')),
                ('distance', models.IntegerField(max_length=15000, verbose_name='distance')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
    ]
