# Generated by Django 3.2.3 on 2021-05-28 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainspa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 28), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='table',
            name='distance',
            field=models.PositiveIntegerField(max_length=15000, verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='table',
            name='quantity',
            field=models.PositiveIntegerField(max_length=1000, verbose_name='quantity'),
        ),
    ]
